#!/bin/bash

dump()
{
	echo "    Exporting existing database"
	
	/usr/bin/mysqldump -uroot --hex-blob --routines --triggers --all-databases > /tmp/mariadb.sql
	mv /tmp/mariadb.sql /app/mariadb/dump.sql
 	/usr/bin/mysqladmin -uroot shutdown
	
	echo "    Successfully exported existing database"
	
	exit
}

trap dump SIGTERM

/usr/bin/mysqld_safe --skip-syslog > /dev/null 2>&1 & wait